"""Compile freestanding C with LLVM and generate persistent native ROM banks."""

import shutil
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent


def tool(name):
    found = shutil.which(name)
    if not found:
        found = shutil.which(name, path="/opt/homebrew/opt/llvm/bin")
    if not found:
        raise SystemExit(f"Install LLVM: missing {name}")
    return found


def mux(values, selector):
    if len(values) == 1:
        return values[0]
    mid = len(values) // 2
    bit = len(values).bit_length() - 2
    return f"({selector}[{bit}] ? {mux(values[mid:], selector)} : {mux(values[:mid], selector)})"


def main():
    out = HERE / "build"
    out.mkdir(exist_ok=True)
    subprocess.run(
        [
            tool("clang"),
            "--target=riscv32-unknown-elf",
            "-march=rv32i",
            "-mabi=ilp32",
            "-Os",
            "-msmall-data-limit=0",
            "-ffreestanding",
            "-fno-builtin",
            "-fno-stack-protector",
            "-nostdlib",
            "-fuse-ld=lld",
            "-Wl,--no-relax",
            f"-Wl,-T,{HERE / 'link.ld'}",
            str(HERE / "start.S"),
            str(HERE / "main.c"),
            "-o",
            str(out / "program.elf"),
        ],
        check=True,
    )
    subprocess.run(
        [tool("llvm-objcopy"), "-O", "binary", str(out / "program.elf"), str(out / "program.bin")],
        check=True,
    )
    listing = subprocess.check_output(
        [tool("llvm-objdump"), "-d", str(out / "program.elf")], text=True
    )
    (out / "program.disasm").write_text(listing)
    image = (out / "program.bin").read_bytes()
    if not 0 < len(image) <= 2048:
        raise SystemExit("Program must fit the 2 KiB ROM window")
    # Banks contain sixteen words, represented by four native eight-bit ROMs.
    banks = (len(image) + 63) // 64
    padded = image.ljust(banks * 64, b"\0")
    lines = ["// Generated by compile.py from main.c and start.S; do not edit."]
    for bank in range(banks):
        for lane in range(4):
            lines += [
                f"module rv32_rom_{bank}_{lane}(input [3:0] address,output [7:0] data);",
                " reg [7:0] cells[0:15];",
                " initial begin",
            ]
            lines += [f" cells[{n}]=8'h{padded[bank * 64 + n * 4 + lane]:02x};" for n in range(16)]
            lines += [" end", " assign data=cells[address];", "endmodule"]
    lines += ["module rv32_rom(input [8:0] address,output [31:0] data);"]
    for bank in range(banks):
        lines += [f" wire [31:0] bank_{bank};"]
        for lane in range(4):
            lines += [
                f" rv32_rom_{bank}_{lane} rom_{bank}_{lane}(address[3:0],"
                f"bank_{bank}[{lane * 8}+:8]);"
            ]
    count = 1 << (banks - 1).bit_length()
    values = [f"bank_{i}" if i < banks else "32'b0" for i in range(count)]
    lines += [
        " wire [4:0] selector=address[8:4];",
        f" assign data=selector<{banks} ? {mux(values, 'selector')} : 32'b0;",
        "endmodule",
    ]
    (HERE / "rv32_rom.v").write_text("\n".join(lines) + "\n")
    sources = [
        "../common/async_ram.v",
        "rv32_registers.v",
        "rv32_shift.v",
        "rv32_alu.v",
        "rv32_decode.v",
        "rv32_lanes.v",
        "rv32_core.v",
        "rv32_rom.v",
        "rv32_bus.v",
        "rv32_demo.v",
    ]
    for format_, filename in [("legacy", "riscv"), ("canonical-v1", "riscv-v1")]:
        manifest = (
            "[verilog]\nsources=[" + ",".join(f'"{s}"' for s in sources) + "]\n"
            'top="rv32_demo"\nclocks=["clk"]\n'
            + f'format="{format_}"\noutput="build/{filename}.cv"\n\n'
            '[[scenario]]\nname="compiled C: calls, stack, loop, byte lanes"\n'
            "setup=[{inputs={clk=0,rst=1,run=1},sample=false},{inputs={rst=0},sample=false}]\nsteps=[\n"
        )
        manifest += (
            "".join(
                " {inputs={clk=1},sample=true},\n {inputs={clk=0},sample=false},\n"
                for _ in range(800)
            )
            + "]\n"
        )
        (
            HERE / ("cvgen-verilog.toml" if format_ == "legacy" else "cvgen-verilog-v1.toml")
        ).write_text(manifest)
    print(f"Compiled {len(image)} bytes of RV32I code into {banks * 4} persistent ROM banks")


if __name__ == "__main__":
    main()
