// Generated by compile.py from main.c and start.S; do not edit.
module rv32_rom_0_0(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h37;
 cells[1]=8'h97;
 cells[2]=8'h93;
 cells[3]=8'h17;
 cells[4]=8'h13;
 cells[5]=8'h97;
 cells[6]=8'h93;
 cells[7]=8'h63;
 cells[8]=8'h03;
 cells[9]=8'h23;
 cells[10]=8'h93;
 cells[11]=8'h13;
 cells[12]=8'h6f;
 cells[13]=8'h97;
 cells[14]=8'h93;
 cells[15]=8'h17;
 end
 assign data=cells[address];
endmodule
module rv32_rom_0_1(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h11;
 cells[1]=8'h02;
 cells[2]=8'h82;
 cells[3]=8'h03;
 cells[4]=8'h03;
 cells[5]=8'h03;
 cells[6]=8'h83;
 cells[7]=8'h7c;
 cells[8]=8'hce;
 cells[9]=8'h00;
 cells[10]=8'h82;
 cells[11]=8'h03;
 cells[12]=8'hf0;
 cells[13]=8'h02;
 cells[14]=8'h82;
 cells[15]=8'h03;
 end
 assign data=cells[address];
endmodule
module rv32_rom_0_2(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h00;
 cells[1]=8'h00;
 cells[2]=8'h42;
 cells[3]=8'h00;
 cells[4]=8'h43;
 cells[5]=8'h00;
 cells[6]=8'h03;
 cells[7]=8'h73;
 cells[8]=8'h02;
 cells[9]=8'hc3;
 cells[10]=8'h12;
 cells[11]=8'h13;
 cells[12]=8'hdf;
 cells[13]=8'h00;
 cells[14]=8'h02;
 cells[15]=8'h00;
 end
 assign data=cells[address];
endmodule
module rv32_rom_0_3(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h00;
 cells[1]=8'h00;
 cells[2]=8'h1a;
 cells[3]=8'h00;
 cells[4]=8'h7f;
 cells[5]=8'h00;
 cells[6]=8'h7f;
 cells[7]=8'h00;
 cells[8]=8'h00;
 cells[9]=8'h01;
 cells[10]=8'h00;
 cells[11]=8'h00;
 cells[12]=8'hfe;
 cells[13]=8'h00;
 cells[14]=8'h7d;
 cells[15]=8'h00;
 end
 assign data=cells[address];
endmodule
module rv32_rom_1_0(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h13;
 cells[1]=8'h63;
 cells[2]=8'h23;
 cells[3]=8'h93;
 cells[4]=8'h6f;
 cells[5]=8'h97;
 cells[6]=8'he7;
 cells[7]=8'hb7;
 cells[8]=8'h23;
 cells[9]=8'h13;
 cells[10]=8'h23;
 cells[11]=8'h6f;
 cells[12]=8'h37;
 cells[13]=8'h83;
 cells[14]=8'h13;
 cells[15]=8'h13;
 end
 assign data=cells[address];
endmodule
module rv32_rom_1_1(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h03;
 cells[1]=8'hf8;
 cells[2]=8'h80;
 cells[3]=8'h82;
 cells[4]=8'hf0;
 cells[5]=8'h00;
 cells[6]=8'h80;
 cells[7]=8'h12;
 cells[8]=8'ha0;
 cells[9]=8'h03;
 cells[10]=8'ha2;
 cells[11]=8'h00;
 cells[12]=8'h15;
 cells[13]=8'h25;
 cells[14]=8'h06;
 cells[15]=8'h05;
 end
 assign data=cells[address];
endmodule
module rv32_rom_1_2(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'hc3;
 cells[1]=8'h62;
 cells[2]=8'h02;
 cells[3]=8'h12;
 cells[4]=8'h5f;
 cells[5]=8'h00;
 cells[6]=8'hc0;
 cells[7]=8'h00;
 cells[8]=8'ha2;
 cells[9]=8'h10;
 cells[10]=8'h62;
 cells[11]=8'h00;
 cells[12]=8'h00;
 cells[13]=8'h05;
 cells[14]=8'h70;
 cells[15]=8'hd0;
 end
 assign data=cells[address];
endmodule
module rv32_rom_1_3(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h7c;
 cells[1]=8'h00;
 cells[2]=8'h00;
 cells[3]=8'h00;
 cells[4]=8'hff;
 cells[5]=8'h00;
 cells[6]=8'h01;
 cells[7]=8'h00;
 cells[8]=8'h00;
 cells[9]=8'h00;
 cells[10]=8'h00;
 cells[11]=8'h00;
 cells[12]=8'h00;
 cells[13]=8'h80;
 cells[14]=8'h00;
 cells[15]=8'hff;
 end
 assign data=cells[address];
endmodule
module rv32_rom_2_0(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h63;
 cells[1]=8'hb7;
 cells[2]=8'h03;
 cells[3]=8'h63;
 cells[4]=8'h67;
 cells[5]=8'h13;
 cells[6]=8'h23;
 cells[7]=8'h23;
 cells[8]=8'h23;
 cells[9]=8'h23;
 cells[10]=8'h23;
 cells[11]=8'h93;
 cells[12]=8'h13;
 cells[13]=8'h23;
 cells[14]=8'h13;
 cells[15]=8'h93;
 end
 assign data=cells[address];
endmodule
module rv32_rom_2_1(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h98;
 cells[1]=8'h15;
 cells[2]=8'ha6;
 cells[3]=8'h04;
 cells[4]=8'h80;
 cells[5]=8'h01;
 cells[6]=8'h26;
 cells[7]=8'h24;
 cells[8]=8'h22;
 cells[9]=8'h20;
 cells[10]=8'h2e;
 cells[11]=8'h04;
 cells[12]=8'h04;
 cells[13]=8'ha2;
 cells[14]=8'h09;
 cells[15]=8'h09;
 end
 assign data=cells[address];
endmodule
module rv32_rom_2_2(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'hc5;
 cells[1]=8'h00;
 cells[2]=8'h45;
 cells[3]=8'h06;
 cells[4]=8'h00;
 cells[5]=8'h01;
 cells[6]=8'h11;
 cells[7]=8'h81;
 cells[8]=8'h91;
 cells[9]=8'h21;
 cells[10]=8'h31;
 cells[11]=8'h00;
 cells[12]=8'h10;
 cells[13]=8'h85;
 cells[14]=8'h81;
 cells[15]=8'h60;
 end
 assign data=cells[address];
endmodule
module rv32_rom_2_3(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h00;
 cells[1]=8'h00;
 cells[2]=8'h80;
 cells[3]=8'h00;
 cells[4]=8'h00;
 cells[5]=8'hfd;
 cells[6]=8'h02;
 cells[7]=8'h02;
 cells[8]=8'h02;
 cells[9]=8'h03;
 cells[10]=8'h01;
 cells[11]=8'h00;
 cells[12]=8'h00;
 cells[13]=8'h80;
 cells[14]=8'h00;
 cells[15]=8'h00;
 end
 assign data=cells[address];
endmodule
module rv32_rom_3_0(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h13;
 cells[1]=8'h97;
 cells[2]=8'he7;
 cells[3]=8'h13;
 cells[4]=8'h23;
 cells[5]=8'h03;
 cells[6]=8'h13;
 cells[7]=8'hb3;
 cells[8]=8'he3;
 cells[9]=8'hb7;
 cells[10]=8'h37;
 cells[11]=8'h13;
 cells[12]=8'h13;
 cells[13]=8'hb7;
 cells[14]=8'h23;
 cells[15]=8'h13;
 end
 assign data=cells[address];
endmodule
module rv32_rom_3_1(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h05;
 cells[1]=8'h00;
 cells[2]=8'h80;
 cells[3]=8'h04;
 cells[4]=8'h20;
 cells[5]=8'h25;
 cells[6]=8'h09;
 cells[7]=8'h04;
 cells[8]=8'h10;
 cells[9]=8'h15;
 cells[10]=8'h55;
 cells[11]=8'h06;
 cells[12]=8'h05;
 cells[13]=8'hd6;
 cells[14]=8'ha0;
 cells[15]=8'h85;
 end
 assign data=cells[address];
endmodule
module rv32_rom_3_2(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h04;
 cells[1]=8'h00;
 cells[2]=8'h80;
 cells[3]=8'h14;
 cells[4]=8'ha9;
 cells[5]=8'h09;
 cells[6]=8'h49;
 cells[7]=8'h95;
 cells[8]=8'h34;
 cells[9]=8'h00;
 cells[10]=8'h34;
 cells[11]=8'hb0;
 cells[12]=8'h85;
 cells[13]=8'h00;
 cells[14]=8'ha5;
 cells[15]=8'hf6;
 end
 assign data=cells[address];
endmodule
module rv32_rom_3_3(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h00;
 cells[1]=8'h00;
 cells[2]=8'h0b;
 cells[3]=8'h00;
 cells[4]=8'h00;
 cells[5]=8'h00;
 cells[6]=8'h00;
 cells[7]=8'h00;
 cells[8]=8'hff;
 cells[9]=8'h00;
 cells[10]=8'h12;
 cells[11]=8'h0a;
 cells[12]=8'h67;
 cells[13]=8'h00;
 cells[14]=8'h90;
 cells[15]=8'hde;
 end
 assign data=cells[address];
endmodule
module rv32_rom_4_0(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'ha3;
 cells[1]=8'h23;
 cells[2]=8'h83;
 cells[3]=8'h37;
 cells[4]=8'h13;
 cells[5]=8'h13;
 cells[6]=8'h63;
 cells[7]=8'h83;
 cells[8]=8'h63;
 cells[9]=8'h03;
 cells[10]=8'hb7;
 cells[11]=8'h93;
 cells[12]=8'h63;
 cells[13]=8'h03;
 cells[14]=8'h13;
 cells[15]=8'h63;
 end
 assign data=cells[address];
endmodule
module rv32_rom_4_1(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h80;
 cells[1]=8'h91;
 cells[2]=8'ha6;
 cells[3]=8'hb5;
 cells[4]=8'h07;
 cells[5]=8'h05;
 cells[6]=8'h94;
 cells[7]=8'hc6;
 cells[8]=8'h90;
 cells[9]=8'hd6;
 cells[10]=8'hd6;
 cells[11]=8'h86;
 cells[12]=8'h18;
 cells[13]=8'hc5;
 cells[14]=8'h06;
 cells[15]=8'h10;
 end
 assign data=cells[address];
endmodule
module rv32_rom_4_2(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'hc5;
 cells[1]=8'ha5;
 cells[2]=8'h05;
 cells[3]=8'hef;
 cells[4]=8'h85;
 cells[5]=8'hf0;
 cells[6]=8'he6;
 cells[7]=8'h15;
 cells[8]=8'hc6;
 cells[9]=8'h25;
 cells[10]=8'h00;
 cells[11]=8'hf6;
 cells[12]=8'hd6;
 cells[13]=8'h15;
 cells[14]=8'hb0;
 cells[15]=8'hc5;
 end
 assign data=cells[address];
endmodule
module rv32_rom_4_3(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h90;
 cells[1]=8'h90;
 cells[2]=8'h90;
 cells[3]=8'hcd;
 cells[4]=8'hb7;
 cells[5]=8'hff;
 cells[6]=8'h04;
 cells[7]=8'h90;
 cells[8]=8'h04;
 cells[9]=8'h90;
 cells[10]=8'h00;
 cells[11]=8'hde;
 cells[12]=8'h02;
 cells[13]=8'h90;
 cells[14]=8'h0a;
 cells[15]=8'h02;
 end
 assign data=cells[address];
endmodule
module rv32_rom_5_0(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h03;
 cells[1]=8'hb7;
 cells[2]=8'h93;
 cells[3]=8'h63;
 cells[4]=8'h93;
 cells[5]=8'h13;
 cells[6]=8'h6f;
 cells[7]=8'h13;
 cells[8]=8'h83;
 cells[9]=8'h03;
 cells[10]=8'h83;
 cells[11]=8'h03;
 cells[12]=8'h83;
 cells[13]=8'h13;
 cells[14]=8'h67;
 cells[15]=8'h13;
 end
 assign data=cells[address];
endmodule
module rv32_rom_5_1(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'hd5;
 cells[1]=8'hd5;
 cells[2]=8'h85;
 cells[3]=8'h04;
 cells[4]=8'h04;
 cells[5]=8'h85;
 cells[6]=8'h00;
 cells[7]=8'h05;
 cells[8]=8'h20;
 cells[9]=8'h24;
 cells[10]=8'h24;
 cells[11]=8'h29;
 cells[12]=8'h29;
 cells[13]=8'h01;
 cells[14]=8'h80;
 cells[15]=8'h01;
 end
 assign data=cells[address];
endmodule
module rv32_rom_5_2(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h25;
 cells[1]=8'h00;
 cells[2]=8'hf5;
 cells[3]=8'hb5;
 cells[4]=8'he0;
 cells[5]=8'h04;
 cells[6]=8'h80;
 cells[7]=8'he0;
 cells[8]=8'hc1;
 cells[9]=8'h81;
 cells[10]=8'h41;
 cells[11]=8'h01;
 cells[12]=8'hc1;
 cells[13]=8'h01;
 cells[14]=8'h00;
 cells[15]=8'h01;
 end
 assign data=cells[address];
endmodule
module rv32_rom_5_3(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h90;
 cells[1]=8'h00;
 cells[2]=8'hde;
 cells[3]=8'h00;
 cells[4]=8'hff;
 cells[5]=8'h00;
 cells[6]=8'h00;
 cells[7]=8'hff;
 cells[8]=8'h02;
 cells[9]=8'h02;
 cells[10]=8'h02;
 cells[11]=8'h02;
 cells[12]=8'h01;
 cells[13]=8'h03;
 cells[14]=8'h00;
 cells[15]=8'hff;
 end
 assign data=cells[address];
endmodule
module rv32_rom_6_0(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h23;
 cells[1]=8'h93;
 cells[2]=8'h03;
 cells[3]=8'h33;
 cells[4]=8'h93;
 cells[5]=8'h23;
 cells[6]=8'he3;
 cells[7]=8'h03;
 cells[8]=8'h13;
 cells[9]=8'h67;
 cells[10]=8'h07;
 cells[11]=8'h00;
 cells[12]=8'h00;
 cells[13]=8'h00;
 cells[14]=8'h00;
 cells[15]=8'h00;
 end
 assign data=cells[address];
endmodule
module rv32_rom_6_1(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h26;
 cells[1]=8'h05;
 cells[2]=8'h26;
 cells[3]=8'h06;
 cells[4]=8'h85;
 cells[5]=8'h26;
 cells[6]=8'h98;
 cells[7]=8'h25;
 cells[8]=8'h01;
 cells[9]=8'h80;
 cells[10]=8'h00;
 cells[11]=8'h00;
 cells[12]=8'h00;
 cells[13]=8'h00;
 cells[14]=8'h00;
 cells[15]=8'h00;
 end
 assign data=cells[address];
endmodule
module rv32_rom_6_2(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h01;
 cells[1]=8'h05;
 cells[2]=8'hc1;
 cells[3]=8'ha6;
 cells[4]=8'hf5;
 cells[5]=8'hc1;
 cells[6]=8'h05;
 cells[7]=8'hc1;
 cells[8]=8'h01;
 cells[9]=8'h00;
 cells[10]=8'h00;
 cells[11]=8'h00;
 cells[12]=8'h00;
 cells[13]=8'h00;
 cells[14]=8'h00;
 cells[15]=8'h00;
 end
 assign data=cells[address];
endmodule
module rv32_rom_6_3(input [3:0] address,output [7:0] data);
 reg [7:0] cells[0:15];
 initial begin
 cells[0]=8'h00;
 cells[1]=8'h00;
 cells[2]=8'h00;
 cells[3]=8'h00;
 cells[4]=8'hff;
 cells[5]=8'h00;
 cells[6]=8'hfe;
 cells[7]=8'h00;
 cells[8]=8'h01;
 cells[9]=8'h00;
 cells[10]=8'h00;
 cells[11]=8'h00;
 cells[12]=8'h00;
 cells[13]=8'h00;
 cells[14]=8'h00;
 cells[15]=8'h00;
 end
 assign data=cells[address];
endmodule
module rv32_rom(input [8:0] address,output [31:0] data);
 wire [31:0] bank_0;
 rv32_rom_0_0 rom_0_0(address[3:0],bank_0[0+:8]);
 rv32_rom_0_1 rom_0_1(address[3:0],bank_0[8+:8]);
 rv32_rom_0_2 rom_0_2(address[3:0],bank_0[16+:8]);
 rv32_rom_0_3 rom_0_3(address[3:0],bank_0[24+:8]);
 wire [31:0] bank_1;
 rv32_rom_1_0 rom_1_0(address[3:0],bank_1[0+:8]);
 rv32_rom_1_1 rom_1_1(address[3:0],bank_1[8+:8]);
 rv32_rom_1_2 rom_1_2(address[3:0],bank_1[16+:8]);
 rv32_rom_1_3 rom_1_3(address[3:0],bank_1[24+:8]);
 wire [31:0] bank_2;
 rv32_rom_2_0 rom_2_0(address[3:0],bank_2[0+:8]);
 rv32_rom_2_1 rom_2_1(address[3:0],bank_2[8+:8]);
 rv32_rom_2_2 rom_2_2(address[3:0],bank_2[16+:8]);
 rv32_rom_2_3 rom_2_3(address[3:0],bank_2[24+:8]);
 wire [31:0] bank_3;
 rv32_rom_3_0 rom_3_0(address[3:0],bank_3[0+:8]);
 rv32_rom_3_1 rom_3_1(address[3:0],bank_3[8+:8]);
 rv32_rom_3_2 rom_3_2(address[3:0],bank_3[16+:8]);
 rv32_rom_3_3 rom_3_3(address[3:0],bank_3[24+:8]);
 wire [31:0] bank_4;
 rv32_rom_4_0 rom_4_0(address[3:0],bank_4[0+:8]);
 rv32_rom_4_1 rom_4_1(address[3:0],bank_4[8+:8]);
 rv32_rom_4_2 rom_4_2(address[3:0],bank_4[16+:8]);
 rv32_rom_4_3 rom_4_3(address[3:0],bank_4[24+:8]);
 wire [31:0] bank_5;
 rv32_rom_5_0 rom_5_0(address[3:0],bank_5[0+:8]);
 rv32_rom_5_1 rom_5_1(address[3:0],bank_5[8+:8]);
 rv32_rom_5_2 rom_5_2(address[3:0],bank_5[16+:8]);
 rv32_rom_5_3 rom_5_3(address[3:0],bank_5[24+:8]);
 wire [31:0] bank_6;
 rv32_rom_6_0 rom_6_0(address[3:0],bank_6[0+:8]);
 rv32_rom_6_1 rom_6_1(address[3:0],bank_6[8+:8]);
 rv32_rom_6_2 rom_6_2(address[3:0],bank_6[16+:8]);
 rv32_rom_6_3 rom_6_3(address[3:0],bank_6[24+:8]);
 wire [4:0] selector=address[8:4];
 assign data=selector<7 ? (selector[2] ? (selector[1] ? (selector[0] ? 32'b0 : bank_6) : (selector[0] ? bank_5 : bank_4)) : (selector[1] ? (selector[0] ? bank_3 : bank_2) : (selector[0] ? bank_1 : bank_0))) : 32'b0;
endmodule
