import fs from 'fs';
import { webcrypto } from 'node:crypto';
import { createPinia, setActivePinia } from 'pinia';
import { mount } from '@vue/test-utils';
import { createRouter, createWebHistory } from 'vue-router';
import i18n from '#/locales/i18n';
import { routes } from '#/router';
import vuetify from '#/plugins/vuetify';
import simulator from '#/pages/simulator.vue';
import { setup } from '../src/setup';
import { scopeList } from '../src/circuit';
import { importCanonical } from '../src/data/importCanonical';
import { runAll } from '../src/testbench';
import { errorDetectedGet, errorDetectedSet } from '../src/engine';
vi.mock('codemirror', async (importOriginal) => {
  const actual = await importOriginal();
  return {...actual, fromTextArea:vi.fn(()=>({setValue:()=>{}}))};
});
vi.mock('codemirror-editor-vue3',()=>({defineSimpleMode:vi.fn()}));
test('simulate canonical project', async()=>{
  Object.defineProperty(window,'crypto',{value:webcrypto,configurable:true});
  const pinia=createPinia();setActivePinia(pinia);
  const router=createRouter({history:createWebHistory(),routes});
  const elem=document.createElement('div');document.body.appendChild(elem);
  global.document.createRange=vi.fn(()=>({setEnd:vi.fn(),setStart:vi.fn(),getBoundingClientRect:vi.fn(()=>({x:0,y:0,width:0,height:0,top:0,right:0,bottom:0,left:0})),getClientRects:vi.fn(()=>({item:vi.fn(()=>null),length:0,[Symbol.iterator]:vi.fn(()=>[])}))}));
  global.globalScope=global.globalScope||{};
  mount(simulator,{global:{plugins:[pinia,router,i18n,vuetify]},attachTo:elem});
  setup();
  const projectData=JSON.parse(fs.readFileSync(process.env.CVGEN_PROJECT,'utf8'));
  const loaded=await importCanonical(projectData);
  if(!loaded.success)throw Error(`canonical loader: ${loaded.errors.join('; ')}`);
  const request=JSON.parse(fs.readFileSync(process.env.CVGEN_CASES,'utf8'));
  const top=Object.values(scopeList).find(s=>s.name===request.top);
  if(!top)throw Error(`missing top ${request.top}`);
  const input=top.Input.map(p=>({label:p.label,bitWidth:p.bitWidth,values:request.cases.map(c=>c[p.label].toString(2).padStart(p.bitWidth,'0'))}));
  const output=top.Output.map(p=>({label:p.label,bitWidth:p.bitWidth,values:request.cases.map(()=> '0'.repeat(p.bitWidth))}));
  errorDetectedSet(false);
  const result=runAll({type:'comb',title:'cv-gen check',groups:[{label:'steps',inputs:input,outputs:output,n:request.cases.length}]},top);
  fs.writeFileSync(process.env.CVGEN_REPORT,JSON.stringify({error:errorDetectedGet(),outputs:Object.fromEntries(result.detailed.groups[0].outputs.map(o=>[o.label,o.results]))}));
},300000);
