"""Write a cv-gen manifest that runs a directed DOOM-machine program in CircuitVerse.

The scenario loads the program's non-zero words through the RTL loader port,
then clocks the machine until it exits, sampling every rising edge, so
`cv-gen verilog check` compares native CircuitVerse gates against Verilator on
real execution (loader, banked RAM, lanes, MMIO), not just reset.

    uv run python tools/doom/cv_scenario.py banks
    uv run cv-gen verilog check --manifest examples/doom/build/cvgen-banks.toml
"""

import argparse
import json
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "doom"))
import machine  # noqa: E402

EXAMPLE = ROOT / "examples" / "doom"


def manifest(name):
    work = Path(tempfile.mkdtemp(prefix="doom-cv-"))
    image = machine.assemble(EXAMPLE / "tests" / f"{name}.S", work / f"{name}.bin")
    wad = work / "empty.wad"
    wad.write_bytes(b"")
    out = work / "iss"
    subprocess.run(
        [machine.build_iss(), "--image", image, "--wad", wad, "--out", out, "--quiet"],
        check=True,
        capture_output=True,
    )
    summary = json.loads((out / "summary.json").read_text())
    if summary["fault"] != "none" or summary["exit_code"] != 0:
        raise SystemExit(f"{name} does not exit cleanly on the ISS: {summary}")
    data = image.read_bytes()
    data += b"\0" * (-len(data) % 4)
    words = [(i, int.from_bytes(data[i : i + 4], "little")) for i in range(0, len(data), 4)]

    def step(inputs, sample):
        fields = ",".join(f"{k}={v}" for k, v in inputs.items())
        return f" {{inputs={{{fields}}},sample={'true' if sample else 'false'}}},"

    setup = [step({"clk": 0, "rst": 1, "run": 0}, False), step({"rst": 0}, False)]
    # Each word is presented, then written by a load_enable pulse, as the graphics
    # machine's native loader test does.
    for a, w in words:
        if w:
            setup += [
                step({"load_address": a, "load_data": w}, False),
                step({"load_enable": 1}, False),
                step({"load_enable": 0}, False),
            ]
    setup += [step({"run": 1}, False)]
    lines = []
    for _ in range(summary["cycles"] + 2):
        lines += [step({"clk": 1}, True), step({"clk": 0}, False)]
    base = tomllib.loads((EXAMPLE / "cvgen-verilog.toml").read_text())["verilog"]
    sources = ",".join(f'"../{s}"' for s in base["sources"])
    text = "\n".join(
        [
            "# Generated by tools/doom/cv_scenario.py; do not edit.",
            "[verilog]",
            f"sources=[{sources}]",
            'top="rv32_doom"',
            'clocks=["clk"]',
            'format="legacy"',
            f'output="doom-{name}.cv"',
            "",
            "[[scenario]]",
            f'name="{name}: load through the loader port and run to exit"',
            "setup=[",
            *setup,
            "]",
            "steps=[",
            *lines,
            "]",
        ]
    )
    path = EXAMPLE / "build" / f"cvgen-{name}.toml"
    path.parent.mkdir(exist_ok=True)
    path.write_text(text + "\n")
    return path, sum(1 for _, w in words if w), summary["cycles"]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("program", help="directed program name in examples/doom/tests")
    args = parser.parse_args()
    path, words, cycles = manifest(args.program)
    print(f"{path}: {words} words, {cycles} cycles")


if __name__ == "__main__":
    main()
